### ISSUE TITLE
Can you provide detailed parameter settings, I ran directly to your code and felt something went wrong

### ISSUE THREAD

**Issue by zjrzjr666** [CSer-Tang-hao/BSFA-FSFG#1]
![image](https://user-images.githubusercontent.com/96851653/203535228-c3d3d863-31e8-4369-be14-db2ca3648fba.png)

**Comment by CSer-Tang-hao** [comment]
This code is only to give paper reviewers verification and academic research. 
After the paper is accepted, we will polish and optimize the code.

**Comment by CSer-Tang-hao** [comment]
@zjrzjr666 Hello, I'm sorry for replying so late. Our paper has been accepted by IEEE TCSVT. At present, we have re-checked the code and found no problems. The code can perfectly reproduce the results of the paper!
