### ISSUE TITLE
T-sne可视化

### ISSUE THREAD

**Issue by Zhengzkang** [CSer-Tang-hao/BSFA-FSFG#2]
帅哥，你好，阅读了你的paper后，真的很佩服，关于文中的T-sne可视化我有一些疑问，能否能提供一下code并简单说下具体操作？我将十分感激，感激涕零！

**Comment by CSer-Tang-hao** [comment]
Thanks for your interest in the t-SNE visualization. I am unable to find the code. I will get back to you as soon as I find it.
